[workspace]
resolver = "2"
members = ["apps/client/src-tauri", "crates/entity", "crates/migration"]

[workspace.dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.38"
