/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function setupNewVault(input: SetupVaultInput) {
    return invoke()<SetupVaultResponse>("setup_new_vault", { input })
}

export type ApplicationError = { DatabaseError: string }
export type SetupVaultInput = { name: string; location: string }
export type SetupVaultResponse = { success: boolean; error: ApplicationError | null }
